// <auto-generated />
using System;
using ExcelClone.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExcelClone.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304131630_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExcelClone.Api.Models.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Column")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("StyleJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<Guid>("WorksheetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorksheetId", "Row", "Column");

                    b.HasIndex("WorksheetId", "Row");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("ExcelClone.Api.Models.Workbook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShareToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Workbooks");
                });

            modelBuilder.Entity("ExcelClone.Api.Models.Worksheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkbookId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkbookId");

                    b.ToTable("Worksheets");
                });

            modelBuilder.Entity("ExcelClone.Api.Models.Cell", b =>
                {
                    b.HasOne("ExcelClone.Api.Models.Worksheet", "Worksheet")
                        .WithMany("Cells")
                        .HasForeignKey("WorksheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worksheet");
                });

            modelBuilder.Entity("ExcelClone.Api.Models.Worksheet", b =>
                {
                    b.HasOne("ExcelClone.Api.Models.Workbook", "Workbook")
                        .WithMany("Worksheets")
                        .HasForeignKey("WorkbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workbook");
                });

            modelBuilder.Entity("ExcelClone.Api.Models.Workbook", b =>
                {
                    b.Navigation("Worksheets");
                });

            modelBuilder.Entity("ExcelClone.Api.Models.Worksheet", b =>
                {
                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
